#!/bin/bash


HTTPASSWD_DIR=/home/usuario

HTTPASSWD_USER=usuario

HTTPASSWD_PASSWD=usuario

DB_ROOT_PASSWD=Gatitos.21



# ------------------------------------------------------------------------------ Instalación  LAMP ------------------------------------------------------------------------------ 



apt update

apt install apache2 -y

apt install mysql-server -y

mysql -u root -p Gatitos.21 -Bse 'UPDATE user SET password="usuario" WHERE User="root"'

sudo apt-get -y install mysql-server

apt install php libapache2-mod-php php-mysql -y



# ------------------------------------------------------------------------------ Instalamos aplicación web ------------------------------------------------------------------------------ 

cd /var/www/html 

git clone https://github.com/evilnapsis/bookmedik.git

# Introducimos la base de tados

mysql -u root -p$DB_ROOT_PASSWD < /var/www/html/bookmedik/schema.sql


chown www-data:www-data * -R



# ------------------------------------------------------------------------------ Inslación de herramientas adicionales ------------------------------------------------------------------------------ 

# Descargamos Adminer

mkdir /var/www/html/adminer 

cd /var/www/html/adminer 

wget https://github.com/vrana/adminer/releases/download/v4.7.7/adminer-4.7.7-mysql.php 

mv adminer-4.7.7-mysql.php index.php

# Generamos un password aleatorio para phpMyAdmin

AUTOGENERATED_PASSWD=`tr -dc A-Za-z0-9 < /dev/urandom | head -c 64`

# instalación de phpMyAdmin

echo "phpmyadmin phpmyadmin/reconfigure-webserver multiselect apache2" | debconf-set-selections 

echo "phpmyadmin phpmyadmin/dbconfig-install boolean true" | debconf-set-selections 

echo "phpmyadmin phpmyadmin/mysql/app-pass password $AUTOGENERATED_PASSWD" |debconf-set-selections 

echo "phpmyadmin phpmyadmin/app-password-confirm password $AUTOGENERATED_PASSWD" | debconf-set-selections


apt install phpmyadmin php-mbstring php-zip php-gd php-json php-curl -y

# Instalación de GoAccess

echo "deb http://deb.goaccess.io/ $(lsb_release -cs) main" | sudo tee -a /etc/apt/sources.list.d/goaccess.list 

wget -O - https://deb.goaccess.io/gnugpg.key | sudo apt-key add - 

apt-get update 

apt-get install goaccess -y


mkdir /var/www/html/stats


nohup goaccess /var/log/apache2/access.log -o /var/www/html/stats/index.html --log-format=COMBINED --real-time-html &

htpasswd -c -b $HTTPASSWD_DIR/.htpasswd $HTTPASSWD_USER $HTTPASSWD_PASSWD


systemctl restart apache2
